#!/bin/bash

MYVIMRC=.vimrc
VIMRC=~/.vimrc
NVIMRC=~/.config/nvim/init.vim

if [ -f $VIMRC ]; then
    echo "copied to $VIMRC"
    cp $MYVIMRC $VIMRC
fi

if [ -f $NVIMRC ]; then
    echo "copied to $NVIMRC"
    cp $MYVIMRC $NVIMRC
fi

cp -r .vim_runtime ~/
